# Generated by Django 5.0.7 on 2024-07-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='items',
            field=models.ManyToManyField(to='app.item'),
        ),
    ]
